/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mrkuza (https://sketchfab.com/mrkuza)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/impala-1964-lowrider-c68508c056a34a34997992deb4355166
title: Impala 1964 Lowrider
*/

import React, { useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"
import { useFrame } from "@react-three/fiber"
import useControls from "../utils/hooks/useControls"

export default function Impala(props) {
  const controls = useControls()
  const group = useRef()
  const { nodes, materials, animations } = useGLTF("/impala.gltf")
  const { actions } = useAnimations(animations, group)

  useFrame(() => {})
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[0, 0.19, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        >
          <group name="Root">
            <group
              name="Camera"
              position={[7.18, -8.17, 0]}
              rotation={[1.26, 0.76, 0.22]}
            />
            <group
              name="Camera001"
              position={[6.33, 13.58, 0.19]}
              rotation={[-1.28, 0.68, 2.95]}
            />
            <group name="All" scale={0.59}>
              <group
                name="����������������005"
                position={[0.05, 2.15, -2.63]}
                rotation={[0.69, 0, 0]}
                scale={1.7}
              >
                <group
                  name="����������������006"
                  position={[-1.34, 0.01, -1.41]}
                  scale={0.08}
                >
                  <group
                    name="��������������������000"
                    position={[16.9, -0.01, 0.07]}
                    rotation={[-0.3, 0, -0.3]}
                    scale={[-0.7, -0.7, -20.57]}
                  >
                    <mesh
                      name="��������������������000_0"
                      geometry={nodes["��������������������000_0"].geometry}
                      material={materials.Root}
                    />
                  </group>
                  <group
                    name="����������������008"
                    position={[-4.25, -0.06, -0.03]}
                    scale={1.57}
                  >
                    <group
                      name="��������������002"
                      position={[1.27, 0.02, -0.01]}
                      rotation={[Math.PI, -1.57, 0]}
                      scale={3.91}
                    >
                      <mesh
                        name="��������������002_0"
                        geometry={nodes["��������������002_0"].geometry}
                        material={materials[".014"]}
                      />
                    </group>
                  </group>
                  <group
                    name="����������������007"
                    position={[31.62, -0.01, 0]}
                  >
                    <group
                      name="LFW002"
                      position={[4.32, -0.04, -0.03]}
                      scale={1.56}
                    >
                      <group
                        name="LFW003"
                        position={[-1.39, 0.01, -0.01]}
                        rotation={[0, 1.57, 0]}
                        scale={3.92}
                      >
                        <mesh
                          name="LFW003_0"
                          geometry={nodes.LFW003_0.geometry}
                          material={materials[".017"]}
                        />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
              <group
                name="����������������004"
                position={[0.05, -5.59, -2.09]}
                scale={1.7}
              >
                <group
                  name="����������������003"
                  position={[-1.34, 0.01, -1.41]}
                  scale={0.08}
                >
                  <group
                    name="����������������001"
                    position={[31.62, -0.01, 0]}
                  >
                    <group
                      name="LFW"
                      position={[4.32, -0.04, -0.03]}
                      scale={1.56}
                    >
                      <group
                        name="LFW001"
                        position={[-1.39, 0.01, -0.01]}
                        rotation={[0, 1.57, 0]}
                        scale={3.92}
                      >
                        <mesh
                          name="LFW001_0"
                          geometry={nodes.LFW001_0.geometry}
                          material={materials[".017"]}
                        />
                      </group>
                    </group>
                  </group>
                  <group
                    name="����������������002"
                    position={[-4.25, -0.06, -0.03]}
                    scale={1.57}
                  >
                    <group
                      name="��������������001"
                      position={[1.27, 0.02, -0.01]}
                      rotation={[Math.PI, -1.57, 0]}
                      scale={3.91}
                    >
                      <mesh
                        name="��������������001_0"
                        geometry={nodes["��������������001_0"].geometry}
                        material={materials[".014"]}
                      />
                    </group>
                  </group>
                  <group
                    name="��������������������001"
                    position={[16.9, -0.01, 0.07]}
                    rotation={[-0.3, 0, -0.3]}
                    scale={[-0.7, -0.7, -20.57]}
                  >
                    <mesh
                      name="��������������������001_0"
                      geometry={nodes["��������������������001_0"].geometry}
                      material={materials.Root}
                    />
                  </group>
                </group>
              </group>
            </group>
            <group
              name="������������"
              position={[6.71, -8.91, 4.61]}
              rotation={[0.75, 0.49, -0.87]}
            />
            <group
              name="����������������009"
              position={[-1.75, -0.08, -0.95]}
              scale={0.21}
            >
              <group
                name="����������������"
                position={[12.97, -6.09, -3.98]}
                scale={0.05}
              />
              <group
                name="Torus001"
                position={[12.93, -5.88, -3.99]}
                rotation={[-1.24, 0.01, 1.63]}
                scale={1.26}
              >
                <mesh
                  name="Torus001_0"
                  geometry={nodes.Torus001_0.geometry}
                  material={materials[".008"]}
                />
              </group>
              <group name="Rdoor" position={[-0.64, -8.49, -5.78]} scale={0.3}>
                <group
                  name="������������_1"
                  position={[-0.38, 1.35, 0.63]}
                  scale={15.7}
                >
                  <mesh
                    name="������������_0"
                    geometry={nodes["������������_0"].geometry}
                    material={materials[".006"]}
                  />
                </group>
              </group>
              <group name="Ldoor" position={[16.38, -8.49, -5.78]} scale={0.3}>
                <group
                  name="������������_2"
                  position={[0.55, 1.2, 0.1]}
                  scale={2.05}
                >
                  <mesh
                    name="������������_0_1"
                    geometry={nodes["������������_0_1"].geometry}
                    material={materials[".005"]}
                  />
                </group>
              </group>
              <group
                name="��������������"
                position={[12.97, -6.55, -4.18]}
                rotation={[-1.2, 0, 0]}
                scale={0.46}
              >
                <mesh
                  name="��������������_0"
                  geometry={nodes["��������������_0"].geometry}
                  material={materials[".009"]}
                />
              </group>
              <group
                name="������002"
                position={[7.01, 6.96, -2.9]}
                scale={0.08}
              >
                <mesh
                  name="������002_0"
                  geometry={nodes["������002_0"].geometry}
                  material={materials.Root}
                />
              </group>
              <group
                name="������"
                position={[10.53, -6.24, -8.93]}
                scale={2.32}
              >
                <mesh
                  name="������_0"
                  geometry={nodes["������_0"].geometry}
                  material={materials[".010"]}
                />
              </group>
              <group
                name="������001"
                position={[15.6, -8.14, -7.73]}
                scale={1.09}
              >
                <mesh
                  name="������001_0"
                  geometry={nodes["������001_0"].geometry}
                  material={materials.Root}
                />
              </group>
              <group
                name="������016"
                position={[10.17, -2.86, -5.72]}
                scale={[2.28, 2.06, 2.06]}
              >
                <mesh
                  name="������016_0"
                  geometry={nodes["������016_0"].geometry}
                  material={materials[".011"]}
                />
              </group>
              <group
                name="��������������013"
                position={[13.47, -21.21, -5.49]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.82}
              >
                <mesh
                  name="��������������013_0"
                  geometry={nodes["��������������013_0"].geometry}
                  material={materials.material}
                />
              </group>
              <group
                name="������010"
                position={[11.6, -5.79, -3.63]}
                rotation={[0.03, -0.01, 0.02]}
                scale={1.88}
              >
                <mesh
                  name="������010_0"
                  geometry={nodes["������010_0"].geometry}
                  material={materials[".007"]}
                />
              </group>
              <group
                name="������014"
                position={[7.76, 21.56, -5.6]}
                scale={1.12}
              >
                <mesh
                  name="������014_0"
                  geometry={nodes["������014_0"].geometry}
                  material={materials[".003"]}
                />
              </group>
              <group
                name="��������������010"
                position={[15.17, 21.44, -5.36]}
                rotation={[-1.54, -0.02, -0.01]}
                scale={0.63}
              >
                <mesh
                  name="��������������010_0"
                  geometry={nodes["��������������010_0"].geometry}
                  material={materials[".002"]}
                />
              </group>
              <group
                name="������������������002"
                position={[7.85, -5.46, -0.72]}
                rotation={[1.6, 0, 0]}
                scale={[5.01, 4.9, 4.68]}
              >
                <mesh
                  name="������������������002_0"
                  geometry={nodes["������������������002_0"].geometry}
                  material={materials.material_11}
                />
              </group>
              <group
                name="����������"
                position={[7.83, -20.97, -4.26]}
                scale={0.64}
              >
                <mesh
                  name="����������_0"
                  geometry={nodes["����������_0"].geometry}
                  material={materials[".001"]}
                />
                <mesh
                  name="����������_1"
                  geometry={nodes["����������_1"].geometry}
                  material={materials[".004"]}
                />
              </group>
              <group
                name="������004"
                position={[7.8, -20.97, -5.44]}
                scale={0.19}
              >
                <mesh
                  name="������004_0"
                  geometry={nodes["������004_0"].geometry}
                  material={materials[".019"]}
                />
              </group>
              <group
                name="������012"
                position={[8.01, 5.62, -0.82]}
                scale={0.37}
              >
                <mesh
                  name="������012_0"
                  geometry={nodes["������012_0"].geometry}
                  material={materials[".012"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload("/impala.gltf")
